### ISSUE TITLE
add player, count score, reset (game basics)

### ISSUE THREAD

**Issue by paula-roesler** [paula-roesler/capstone-project#1]
## Value statement

**As** a user
**I want to** add min. 2 and max. 4 player to count their scores
**in order to** determine the player with the lowest score

## Description
![US_01_Scribble](https://user-images.githubusercontent.com/12655010/110330377-f8b5c100-801d-11eb-887f-9d8a21116989.png)

## Acceptance criteria

- [x] Starts with placeholder players (no players)
- [x] Starts with 0 score
- [x] Add Player form adds a player
- [x] must be min 2 and max 4 players to start game
- [x] not possible to remove one player
- [x] reset button resets players and scores

## Tasks

- [x] Create branch
- [x] Create Player component
- [x] Create AddPlayerForm component
- [x] Create CountScoreComponent
- [x] Create Button component
- [x] Write components test
- [x] Implement form logic
- [x] Implement count score logic
- [x] Implement reset logic
- [x] Add missing styles

## Complexity
medium
