### ISSUE TITLE
Scoring per hole

### ISSUE THREAD

**Issue by paula-roesler** [paula-roesler/capstone-project#13]
## Value statement
As a user
I want to count my score for every hole seperate
in order to get an overview of my scoring in relation to the par of the hole

## Description
![Scoring-per-hole](https://user-images.githubusercontent.com/12655010/112349008-a389d880-8cc8-11eb-8b20-c9cf8bac592b.png)

## Acceptance criteria

- [ ] Infos of hole: number, par, distance men, distance women
- [ ] Graphic of hole
- [ ] Navigation button back/next
- [ ] Name of Player with Score button
- [ ] Score is 0 on every new hole and will be deleted
- [ ] 'Save game' button on last hole

## Tasks

- [ ] Create branch
- [ ] Create a page for every hole
- [ ] Save to local storage
- [ ] Write components test

## Complexity
medium
