### ISSUE TITLE
Delete games from history

### ISSUE THREAD

**Issue by paula-roesler** [paula-roesler/capstone-project#14]
## Value statement

As a user
I want to push the "delete game" button
in order to delete a game from history

## Description
![Delete-game-from-history](https://user-images.githubusercontent.com/12655010/112362690-fe293180-8cd4-11eb-821a-ece0aca9642e.png)

## Acceptance criteria

- [x] "Delete game" button on every game
- [x]  response for successfully deletion

## Tasks

- [x] Create branch
- [x] Create "delete game" Button
- [x] Delete from local storage
- [x] Create prompt component
- [x] Write components test

## Complexity
low
