### ISSUE TITLE
Confirm saving game

### ISSUE THREAD

**Issue by paula-roesler** [paula-roesler/capstone-project#16]
## Value statement
As a user
i want to be confirmed about succsessfully saved my game
in order to be sure to have saved my game

## Description
![Confirm-saving-game](https://user-images.githubusercontent.com/12655010/112367132-d6889800-8cd9-11eb-8362-15a39c4272d8.png)

## Acceptance criteria
- [ ] Message must be shown after clicking 'save game'
- [ ] Message disappears automatically after several seconds

## Tasks
- [ ] Create branch
- [ ] Create prompt component
- [ ] set duration to prompt
