### ISSUE TITLE
Displaying scorecard in history

### ISSUE THREAD

**Issue by paula-roesler** [paula-roesler/capstone-project#17]
## Value statement
As a user
i want to see my score in detail for every hole
to be able to determine my performance more pricise

## Description
![Scorecard-in-history](https://user-images.githubusercontent.com/12655010/112368899-dd180f00-8cdb-11eb-9796-fce3636dbe1c.png)

## Acceptance criteria
- [x] Score for every hole (1-18) is shown
- [x] score for every player in game is shown

## Tasks
- [x] Create branch
- [x] Create table component for score
- [x] Save hole and score in table

## Comlexity
medium
