### ISSUE TITLE
Showing weather forecast

### ISSUE THREAD

**Issue by paula-roesler** [paula-roesler/capstone-project#18]
## Value statement
As a user
i want to have a weather forecast
in order to know if i can play golf and what i should wear

## Description
![Weather](https://user-images.githubusercontent.com/12655010/112434056-631b7080-8d43-11eb-96c0-82d719ecfdae.png)

## Acceptance Criteria
- [x] I need to see temperature, precipitation, wind
- [x] i need to have a few days of forecast
- [x] it should be updatet every 15 minutes

## Tasks 
- [x] Create Branch
- [x] Fetch Data from API
- [x] Schow all Details
- [x] Create pages for each forecast day

## Complexity
high
