### ISSUE TITLE
LandingPage

### ISSUE THREAD

**Issue by paula-roesler** [paula-roesler/capstone-project#39]

**Comment by paula-roesler** [comment]
## Value statement
As a user
i want to be welcomed
in order to have an intro to the app

## Description
Landing page with a big play button

## Acceptance criteria
- [ ] Title of the app is shown
- [ ] Big play button is shown

## Tasks
- [ ] Create branch
- [ ] Create landing page component
- [ ] animate the play button
