### ISSUE TITLE
Add "End game" button and page

### ISSUE THREAD

**Issue by paula-roesler** [paula-roesler/capstone-project#4]
## Value statement

As a user
I want to push the "End game" button
in order to determine the player with the lowest score

## Description
![US3 - end game button and winner page](https://user-images.githubusercontent.com/12655010/111144591-89911d00-8587-11eb-984f-db3436fb1931.png)

## Acceptance criteria

- [x] "End game" button shows a new page
- [x] Player with the lowest score is shown as winner
- [x] "Play again" button to start a new game

## Tasks

- [x] Create branch
- [x] Create "End game" Button
- [x] Create winner page component
- [x] Add conditional logic for showing winner page
- [x] Create "New game" Button
- [x] Write components test

## Complexity
medium
