### ISSUE TITLE
Plus-Minus Score Buttons

### ISSUE THREAD

**Issue by paula-roesler** [paula-roesler/capstone-project#41]
## Value statement

As a user
I want to be able to count score plus and minus
in order to be able to update score correctly

## Description
Plus and Minus Buttons on single player

## Acceptance criteria
- [x] the buttons should count correctly
- [x] score should not be able to get negative

## Tasks
- [x] Create branch
- [x] Create count logic
- [x] Create positive number logic

## Complexity
medium
