### ISSUE TITLE
Add "Start game" button and game page

### ISSUE THREAD

**Issue by paula-roesler** [paula-roesler/capstone-project#5]
## Value statement

As a user
I want to push the "Start game" button
in order to get to a seperate page for scoring

## Description
![US2 - start game button   page](https://user-images.githubusercontent.com/12655010/111144162-01127c80-8587-11eb-834e-cf875f187fb0.png)

## Acceptance criteria

- [ ] "Start game" button shows a new page
- [ ] All players Player are displayed with their score
- [ ] score can be counted

## Tasks

- [ ] Create branch
- [ ] Create "End game" Button
- [ ] Create winner page component
- [ ] Add conditional logic for showing winner page
- [ ] Create "New game" Button
- [ ] Write components test

## Complexity
medium
