### ISSUE TITLE
Save winner to history page

### ISSUE THREAD

**Issue by paula-roesler** [paula-roesler/capstone-project#6]
## Value statement

As a user
I want to push the "Save game" button
in order to save the winner of this game in the history

## Description
![US4 - save to local storage](https://user-images.githubusercontent.com/12655010/111146201-72ebc580-8589-11eb-8801-9ca80a448dd0.png)

## Acceptance criteria

- [x] "Save game" button shows a prompt
- [x] Prompt is showing symbol for successfully saved

## Tasks

- [x] Create branch
- [x] Create "Save game" Button
- [x] Save to local storage
- [x] Create prompt component
- [x] Write components test

## Complexity
medium
