### ISSUE TITLE
Game History with navigation

### ISSUE THREAD

**Issue by paula-roesler** [paula-roesler/capstone-project#7]
## Value statement

As a user
I want to be able to navigate to the history page
in order see all played games

## Description
![US5 - save to local storage](https://user-images.githubusercontent.com/12655010/111167323-4774d500-85a1-11eb-9cfb-084eb66d5894.png)

## Acceptance criteria

- [x] have a list of all games
- [x] navigate to 'new game' page

## Tasks

- [x] Create branch
- [x] Create history page component
- [x] Display Games from local storage
- [x] Create navigation with history and new game
- [x] Write components test

## Complexity
medium
